name: Build Docker image and test locally
on: pull_request

jobs:
    buildAndTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build an image image and test locally
              run: |
                  docker build -t thinkthenrant/containerized-aws-cdk:latest .
                  docker build -t thinkthenrant/containerized-aws-cdk/aws-cdk:latest .
                  mkdir myCdkApp
                  docker run -v $PWD/myCdkApp:/myCdkApp -w=/myCdkApp thinkthenrant/containerized-aws-cdk:latest -t
                  docker run -v $PWD/myCdkApp:/myCdkApp -w=/myCdkApp thinkthenrant/containerized-aws-cdk/aws-cdk:latest -t