name: Publish Docker image
on:
    push:
        branches:
            - master
        tags:
            - 'cdk-release*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build and publish to DockerHub
          uses: elgohr/Publish-Docker-Github-Action@2.11
          with:
            name: thinkthenrant/containerized-aws-cdk
            username: thinkthenrant
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            tag_names: true
        - name: Build and publish to GitHub Packages
          uses: elgohr/Publish-Docker-Github-Action@2.11
          with:
            # publish to github package instead of DockerHub
            registry: docker.pkg.github.com
            name: thinkthenrant/containerized-aws-cdk/aws-cdk
            username: hencrice
            password: ${{ secrets.GITHUB_PACKAGE_PSA_TOKEN }}
            tag_names: true