name: Publish Docker image
on:
    push:
        branches:
            - master
        tags:
            - 'v*-cdk-release*'

jobs:
    buildTestRelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build an image image and test locally
              run: |
                  docker build -t thinkthenrant/containerized-aws-cdk:latest .
                  docker build -t thinkthenrant/containerized-aws-cdk/aws-cdk:latest .
                  mkdir myCdkApp
                  docker run -v $PWD/myCdkApp:/myCdkApp -w=/myCdkApp thinkthenrant/containerized-aws-cdk:latest -t
                  docker run -v $PWD/myCdkApp:/myCdkApp -w=/myCdkApp thinkthenrant/containerized-aws-cdk/aws-cdk:latest -t
            - name: Publish to DockerHub
              uses: elgohr/Publish-Docker-Github-Action@2.11
              with:
                  name: thinkthenrant/containerized-aws-cdk
                  username: thinkthenrant
                  password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
                  tag_names: true
            - name: Build and publish to GitHub Packages
              uses: elgohr/Publish-Docker-Github-Action@2.11
              with:
                  # publish to github package instead of DockerHub
                  registry: docker.pkg.github.com
                  name: thinkthenrant/containerized-aws-cdk/aws-cdk
                  username: hencrice
                  password: ${{ secrets.GITHUB_PACKAGE_PSA_TOKEN }}
                  tag_names: true